

name: Building Docker image


on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
     
      - uses: actions/checkout@v3

      
      - name: Build docker image
        run: docker build -t pramod003/sample_app .

     
  login:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: login to dockerhub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
  push:
    runs-on: ubuntu-latest
    needs: login
    steps:
     - name: Build and push to dockerhub -repository
       uses: docker/build-push-action@v3
       with:
         push: true
         tags: user/app:latest
  
